// src/content/loaders.ts — lazy, per-topic content loading.
//
// Each topic's content is a side-effecting module that registers itself when
// imported. Loading them all eagerly would put ~690 kB of study content in the
// initial bundle, so TopicPage pulls only the module for the route it renders.
// The explicit map (rather than a template literal) keeps the imports statically
// analyzable, so Vite can code-split each one.

export const CONTENT_LOADERS: Record<string, () => Promise<unknown>> = {
  "ai-advanced-rag": () => import("./ai-advanced-rag"),
  "ai-agent-memory": () => import("./ai-agent-memory"),
  "ai-agents": () => import("./ai-agents"),
  "ai-embeddings": () => import("./ai-embeddings"),
  "ai-llm": () => import("./ai-llm"),
  "ai-multi-agent": () => import("./ai-multi-agent"),
  "ai-orchestration": () => import("./ai-orchestration"),
  "ai-rag": () => import("./ai-rag"),
  "ai-rag-eval": () => import("./ai-rag-eval"),
  "ai-system-design": () => import("./ai-system-design"),
  "ai-tool-calling": () => import("./ai-tool-calling"),
  "ai-vector-db": () => import("./ai-vector-db"),
  "dsa-arrays": () => import("./dsa-arrays"),
  "dsa-backtracking": () => import("./dsa-backtracking"),
  "dsa-binary-tree": () => import("./dsa-binary-tree"),
  "dsa-bst": () => import("./dsa-bst"),
  "dsa-dp": () => import("./dsa-dp"),
  "dsa-graph": () => import("./dsa-graph"),
  "dsa-greedy": () => import("./dsa-greedy"),
  "dsa-hashmaps": () => import("./dsa-hashmaps"),
  "dsa-heap": () => import("./dsa-heap"),
  "dsa-linked-list": () => import("./dsa-linked-list"),
  "dsa-queue": () => import("./dsa-queue"),
  "dsa-sliding-window": () => import("./dsa-sliding-window"),
  "dsa-stack": () => import("./dsa-stack"),
  "dsa-strings": () => import("./dsa-strings"),
  "dsa-two-pointers": () => import("./dsa-two-pointers"),
  "py-asyncio": () => import("./py-asyncio"),
  "py-concurrency": () => import("./py-concurrency"),
  "py-decorators": () => import("./py-decorators"),
  "py-fastapi": () => import("./py-fastapi"),
  "py-functions": () => import("./py-functions"),
  "py-fundamentals": () => import("./py-fundamentals"),
  "py-gil": () => import("./py-gil"),
  "py-interview": () => import("./py-interview"),
  "py-iterators": () => import("./py-iterators"),
  "py-oop": () => import("./py-oop"),
  "react-architecture": () => import("./react-architecture"),
  "react-fundamentals": () => import("./react-fundamentals"),
  "react-hooks": () => import("./react-hooks"),
  "react-interview": () => import("./react-interview"),
  "react-performance": () => import("./react-performance"),
  "react-rendering": () => import("./react-rendering"),
  "react-state": () => import("./react-state"),
  "sd-api": () => import("./sd-api"),
  "sd-caching": () => import("./sd-caching"),
  "sd-databases": () => import("./sd-databases"),
  "sd-distributed": () => import("./sd-distributed"),
  "sd-event-driven": () => import("./sd-event-driven"),
  "sd-load-balancing": () => import("./sd-load-balancing"),
  "sd-microservices": () => import("./sd-microservices"),
  "sd-queues": () => import("./sd-queues"),
  "sd-realworld": () => import("./sd-realworld"),
  "sd-replication": () => import("./sd-replication"),
  "sd-scalability": () => import("./sd-scalability"),
  "sd-sharding": () => import("./sd-sharding"),
};
